export const LIST_COMMENTS_REQUEST = "LIST_COMMENTS_REQUEST";
export const LIST_COMMENTS_SUCCESS = "LIST_COMMENTS_SUCCESS";
export const LIST_COMMENTS_FAIL = "LIST_COMMENTS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";
