export const LIST_TOPICS_REQUEST = "LIST_TOPICS_REQUEST";
export const LIST_TOPICS_SUCCESS = "LIST_TOPICS_SUCCESS";
export const LIST_TOPICS_FAIL = "LIST_TOPICS_FAIL";

export const LIST_ALL_TOPICS_REQUEST = "LIST_ALL_TOPICS_REQUEST";
export const LIST_ALL_TOPICS_SUCCESS = "LIST_ALL_TOPICS_SUCCESS";
export const LIST_ALL_TOPICS_FAIL = "LIST_ALL_TOPICS_FAIL";

export const ADD_NEW_TOPIC_REQUEST = "ADD_NEW_TOPIC_REQUEST";
export const ADD_NEW_TOPIC_SUCCESS = "ADD_NEW_TOPIC_SUCCESS";
export const ADD_NEW_TOPIC_FAIL = "ADD_NEW_TOPIC_FAIL";
